POST /benutzer HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "vName": "Apache",
  "nName": "BleibtGleich",
  "email": "apache@bleibtgleich.de",
  "passwort": "1234"
}

###
DELETE /benutzer/apache@bleibtgleich.de HTTP/2
Host: localhost:8080

###
GET  /benutzer/apache@bleibtgleich.de HTTP/2
Host: localhost:8080

###
PUT /benutzer/apache@bleibtgleich.de HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "vName": "ApacheEdit",
  "nName": "BleibtEdit",
  "passwort": "edit1234"
}
###


POST /benutzer HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "vName": "Artir",
  "nName": "Guri",
  "email": "artir.guri@outlook.de",
  "passwort": "1234"
}
###
DELETE /benutzer/artir.guri@outlook.de HTTP/2
Host: localhost:8080


###nachher in Nachrichten http auslagern - mit git wird momentan overwritten?
###NACHRICHTEN

DELETE /nachrichten/abcd HTTP/2
Host: localhost:8080