###

POST /benutzer HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "vName": "Apache",
  "nName": "BleibtGleich",
  "email": "apache@bleibtgleich.de",
  "passwort": "1234"
}

###
DELETE /benutzer/apache@bleibtgleich.de HTTP/2
Host: localhost:8080
