POST /nachricht HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "vName": "Apache",
  "nName": "Bleibt Gleich",
  "email": "apache@bleibtgleich.de",
  "betreff": "Treppenhaus",
  "nachricht": "Rmmmmm, Rmmmm!"
}

###

POST /nachricht HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "vName": "Apache",
  "nName": "Bleibt Gleich",
  "email": "apache@bleibtgleich.de",
  "betreff":"xyz",
  "nachricht": "DROP TABLE nachrichten"
}

###
###PUT
###

PUT /nachricht/xyz HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "nachricht": "Nachricht nach PUT"
}